package edu.monmouth.cs250.s1328134.njbirdwatching

object BirdFamilyNames {

    // for dropdown
    val birdFamilyNames : ArrayList<String> = arrayListOf(
        "All",
        "Ducks, Geese, and Waterfowl",
        "New World Quail",
        "Pheasants, Grouse, and Allies",
        "Grebes",
        "Pigeons and Doves",
        "Cuckoos",
        "Nightjars and Allies",
        "Swifts",
        "Hummingbirds",
        "Rails, Gallinules, and Coots",
        "Cranes",
        "Stilts and Avocets",
        "Oystercatchers",
        "Plovers and Lapwings",
        "Sandpipers and Allies",
        "Skuas and Jaegers",
        "Auks, Murres, and Puffins",
        "Gulls, Terns, and Skimmers",
        "Tropicbirds",
        "Loons",
        "Albatrosses",
        "Southern Storm-Petrels",
        "Northern Storm-Petrels",
        "Shearwaters and Petrels",
        "Storks",
        "Frigatebirds",
        "Boobies and Gannets",
        "Anhingas",
        "Cormorants and Shags",
        "Pelicans",
        "Herons, Egrets, and Bitterns",
        "Ibises and Spoonbills",
        "New World Vultures",
        "Osprey",
        "Hawks, Eagles, and Kites",
        "Barn-Owls",
        "Owls",
        "Kingfishers",
        "Woodpeckers",
        "Falcons and Caracaras",
        "New World and African Parrots",
        "Tyrant Flycatchers",
        "Vireos, Shrike-Babblers, and Erpornis",
        "Shrikes",
        "Crows, Jays, and Magpies",
        "Tits, Chickadees, and Titmice",
        "Larks",
        "Swallows",
        "Kinglets",
        "Waxwings",
        "Nuthatches",
        "Treecreepers",
        "Gnatcatchers",
        "Wrens",
        "Mockingbirds and Thrashers",
        "Starlings",
        "Thrushes and Allies",
        "Old World Flycatchers",
        "Old World Sparrows",
        "Wagtails and Pipits",
        "Finches, Euphonias, and Allies",
        "Longspurs and Snow Buntings",
        "New World Sparrows",
        "Yellow-breasted Chat",
        "Troupials and Allies",
        "New World Warblers",
        "Cardinals and Allies"
    )

    // I did not get to make icons for some bird families, so this list is used for icons so that those birds get the default icon but still have a dropdown.
    private val forIcons : ArrayList<String> = arrayListOf(
        "Ducks, Geese, and Waterfowl",
        //"New World Quail",
        "Pheasants, Grouse, and Allies",
        "Grebes",
        "Pigeons and Doves",
        "Cuckoos",
        "Nightjars and Allies",
        "Swifts",
        "Hummingbirds",
        "Rails, Gallinules, and Coots",
        "Cranes",
        "Stilts and Avocets",
        //"Oystercatchers",
        "Plovers and Lapwings",
        "Sandpipers and Allies",
        "Skuas and Jaegers",
        "Auks, Murres, and Puffins",
        "Gulls, Terns, and Skimmers",
        //"Tropicbirds",
        "Loons",
        //"Albatrosses",
        "Southern Storm-Petrels",
        "Northern Storm-Petrels",
        "Shearwaters and Petrels",
        "Storks",
        //"Frigatebirds",
        "Boobies and Gannets",
        "Anhingas",
        "Cormorants and Shags",
        //"Pelicans",
        "Herons, Egrets, and Bitterns",
        "Ibises and Spoonbills",
        //"New World Vultures",
        //"Osprey",
        "Hawks, Eagles, and Kites",
        "Barn-Owls",
        "Owls",
        //"Kingfishers",
        "Woodpeckers",
        "Falcons and Caracaras",
        "New World and African Parrots",
        "Tyrant Flycatchers",
        "Vireos, Shrike-Babblers, and Erpornis",
        //"Shrikes",
        "Crows, Jays, and Magpies",
        "Tits, Chickadees, and Titmice",
        //"Larks",
        "Swallows",
        //"Kinglets",
        //"Waxwings",
        "Nuthatches",
        //"Treecreepers",
        //"Gnatcatchers",
        "Wrens",
        "Mockingbirds and Thrashers",
        //"Starlings",
        "Thrushes and Allies",
        //"Old World Flycatchers",
        "Old World Sparrows",
        //"Wagtails and Pipits",
        "Finches, Euphonias, and Allies",
        "Longspurs and Snow Buntings",
        "New World Sparrows",
        "Yellow-breasted Chat",
        "Troupials and Allies",
        "New World Warblers",
        "Cardinals and Allies"
    )

    // for icons
    val birdImageNames : ArrayList<String> = forIcons.map {it.replace(" ","_").replace(",","").replace("-","").lowercase()} as ArrayList<String>

}

